### ISSUE TITLE
Development continuation?

### ISSUE THREAD

**Issue by rurouni-hou-ou** [TTG-Still-No-Name-Yet/TTG#11]
So, it's been at least a month since we last worked on this project. We were becoming quite proud of it too. But of course, we know it is a little broken. But GitHub is version control so we can roll back to when the code was working and re-develop from there. That is, if people want to. I know we are all busy at this point, but would anyone be interested in continuing this project with me?

**Comment by rurouni-hou-ou** [comment]
This is plainly not that worth fixing. After testing by @MarkStudiosOfficial , MonoGame and XNA seem to have been updated and messed up support for our code.

**Comment by MarkStudiosOfficial** [comment]
I will reopen this issue/discussion due to the fact that the code is in fact portable as we could either do a rewrite of the actual game using the new version of MonoGame only instead of relying on XNA or a C++ port of the code/rewrite which I will do either of them when I have actual time to do development from porting my application from Java to C#. If you still want to do that then let me know if you want to do the rewrite or scrap the full project and start again at the next TTG

**Comment by rurouni-hou-ou** [comment]
Shall we just go with the re-write, since we already have half of it written on MonoGame? Or we could do a C++ port if it would take the same amount of effort.

**Comment by MarkStudiosOfficial** [comment]
Just go for the rewrite as it will be easier to do and we know we will get something out of it. End of discussion :)
